---
abstract: unknown
author:
  - 'Alexander Nalobin <alexander@nalobin.ru>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Date-Holidays-RU
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
  Time::Piece: 0
version: 0.01
